# Generated by Django 5.1.3 on 2024-11-19 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='content_image',
            field=models.ImageField(blank=True, null=True, upload_to='stories/images/'),
        ),
    ]
