# Generated by Django 5.1.3 on 2024-11-20 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0002_story_content_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='story',
            old_name='content_url',
            new_name='description',
        ),
    ]
