# Generated by Django 5.1.3 on 2024-11-22 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0003_rename_content_url_story_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
