name: Deploy Django App to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Deploy to EC2
        env:
          SSH_PRIVATE_KEY: ${{ secrets.AWS_SSH_KEY }}
          HOST: ${{ secrets.AWS_EC2_HOST }}
        run: |
          ssh -o StrictHostKeyChecking=no -i "$SSH_PRIVATE_KEY" ubuntu@$HOST << EOF
            cd /path/to/your/app
            git pull origin main
            source /path/to/venv/bin/activate
            pip install -r requirements.txt
            python manage.py migrate
            python manage.py collectstatic --noinput
            sudo systemctl restart gunicorn
          EOF
